# Generated by Django 2.2.10 on 2020-04-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='file_msg',
            field=models.FileField(blank=True, upload_to='Chat/files'),
        ),
    ]
