# Generated by Django 2.2.10 on 2020-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messages_file_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group_image',
            field=models.ImageField(default='accounts/images/default_group_image.png', upload_to='accounts/images/'),
        ),
    ]
