# Generated by Django 2.2.10 on 2020-04-28 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20200422_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group_admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='group_name',
            field=models.TextField(null=True),
        ),
    ]
