# Generated by Django 2.2.10 on 2020-04-28 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200428_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='group_admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='roomie',
            field=models.ManyToManyField(blank=True, related_name='roommate', to=settings.AUTH_USER_MODEL),
        ),
    ]
