# Generated by Django 2.2.10 on 2020-05-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200428_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='group_admins',
        ),
    ]
