# Generated by Django 2.2.10 on 2020-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chatroom_group_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='file_type',
            field=models.TextField(blank=True),
        ),
    ]
