# Generated by Django 2.2.10 on 2020-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200402_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='accounts/images/default_profile_image.png', upload_to='accounts/images/'),
        ),
    ]
